artifact_location: file:///C:/Users/jcwin/OneDrive - University of Southampton/_Southampton/2024-25/Star-Classifier/mlflow/388374043760357004
creation_time: 1729184230130
experiment_id: '388374043760357004'
last_update_time: 1729260412300
lifecycle_stage: active
name: LAMOST_ConVnet
tags: {}
