aliases: []
creation_timestamp: 1729184420535
current_stage: None
description: null
last_updated_timestamp: 1729184420535
name: tracking-quickstart
run_id: c5d57b7505c14522b8695e0a58b22edd
run_link: null
source: file:///C:/Users/jcwin/OneDrive - University of Southampton/_Southampton/2024-25/Star-Classifier/mlflow/388374043760357004/c5d57b7505c14522b8695e0a58b22edd/artifacts/iris_model
status: READY
status_message: null
storage_location: file:///C:/Users/jcwin/OneDrive - University of Southampton/_Southampton/2024-25/Star-Classifier/mlflow/388374043760357004/c5d57b7505c14522b8695e0a58b22edd/artifacts/iris_model
user_id: null
version: 1
